### ISSUE TITLE
Video audio not included after export

### ISSUE THREAD

**Issue by ahmedsafadii** [hexagons/PixelKit#11]
I'm sorry about this issue and sorry about those things,

but when I export the video using it export only the video without the audio channel,

Note if I did that flag to true,
RecordPIX.recordAudio = true

it will record the microphone audio along with video audio,
is it possible to export the video ad audio without enabling the microphone?

**Comment by hexagons** [comment]
Hey, no worries, I'm glad PixelKit is being used.
Unfortunately I have not built a way to pass the audio video to the recorder yet.

Tho I am experimenting with this in [`PixelMerger`](https://github.com/hexagons/PixelMerger):
~~~swift
mergeMix(name: "<name>", videoUrl: <url-to-rendered-video>, videosWithAudio: [VideoWithAudio], success: { url in }, failure: { error in })
~~~
Here's the [method](https://github.com/hexagons/PixelMerger/blob/master/Sources/PixelMerger.swift#L285).

For now I recommend combining the video and audio with a separate tool in post.

I will add this to the PixelKit feature request list!

**Comment by ahmedsafadii** [comment]
Will no worries, I just had to tell you about this, otherwise, it looks amazing library, 
for me, the fix is merging atm like what you doing above.

Keep going.  <3
