### ISSUE TITLE
Memory Leak (iPhone XS Max crash)

### ISSUE THREAD

**Issue by anonrig** [hexagons/PixelKit#12]
<img width="854" alt="Screen Shot 2020-04-22 at 4 50 18 AM" src="https://user-images.githubusercontent.com/1935246/79932042-308f3680-8455-11ea-8a86-23429a808dde.png">

I'm using the following code to create an initial alpha layer called `threshold` and then multiplying it with border color. The code below is only run once.

```swift
 let fullscreenBackground = ColorPIX(at: .fullscreen)
    fullscreenBackground.color = .clear
    
    let blended: BlendPIX = fullscreenBackground & imagePix
    
    let mask: ReorderPIX = ReorderPIX()
    mask.inputA = blended
    mask.inputB = blended
    mask.redChannel = .alpha
    mask.greenChannel = .alpha
    mask.blueChannel = .alpha
    mask.alphaChannel = .one
    
    threshold = blended._blur(0.1)._threshold(0.1)._lumaToAlpha()
    
    let borderColor = LiveColor(color)
    let colorEdge = threshold! * borderColor
    
    let final: PIX = colorEdge & imagePix
    final.delegate = self
```

Later by changing the color I'm calling this following method on a debounce of 2 seconds:
```swift
guard let threshold = threshold else { return }
    let borderColor = LiveColor(color)
    let colorEdge = threshold * borderColor
    
    let final: PIX = colorEdge & imagePix
    final.delegate = self
```

**Comment by hexagons** [comment]
Hi, so in your debounced loop you are creating two new BlendPIXs with multiply (`*`) and over (`&`), this is causing the leak, you can avoid this by re-using pipeline you setup in your first block. The  LiveColor has a [initializer with a future callback](http://hexagons.se/live-values/Classes/LiveColor.html#/s:10LiveValues0A5ColorCyACSo7UIColorCyccfc), simply swap `LiveColor(color)` with `LiveColor({ self.color })`, then as soon as you change the `UIColor` / `NSColor`, all relevant PIXs will render, and the final PIXs delegate will be called. [LiveValues](https://github.com/hexagons/LiveValues) simply listen for new values on each frame. 

You can monitor the active PIXs in the [Render](http://pixelkit.net/docs/Classes/PixelKit.html#/s:8PixelKitAAC6renderXevp)'s [`linkedNodes`](http://renderkit.info/Classes/Render.html#/s:9RenderKit0A0C11linkedNodesSayAA4NODE_pGvp).
There is currently not auto release of PIXs. Please call [`destroy()`](http://pixelkit.net/docs/Classes/PIX.html#/s:8PixelKit3PIXC7destroyyyF) to release the texture of a PIX.

Let me know if it works!
