### ISSUE TITLE
ScenePIX setup

### ISSUE THREAD

**Issue by abbana** [hexagons/PixelKit#13]
Hi,

first off, congrats for the great work done.

I want to apply flarePIX into Scenekit via ScenePIX , but ScenePIX is undocumented.

I see

public func setup(cameraNode: SCNNode, scene: SCNScene, sceneView: SCNView) 

what is the correct way to apply scenePIX to Scenekit?

Thanks.

**Comment by hexagons** [comment]
Hi, yes, you got it, `setup(cameraNode:scene:sceneView:)`is correct.
You can also just set `cameraNode`,
`scene` & `sceneView` individually.
I will update the docs to include the convenience function.
Thanks for the kudos. I'm glad you found a unique use case.

**Comment by abbana** [comment]
Thanks!
