### ISSUE TITLE
install PixelKit error

### ISSUE THREAD

**Issue by quinn0809** [hexagons/PixelKit#4]
I'd love PixelKit,but,I find that ,Unable to find a pod with name, author, summary, or description matching `PixelKit`

**Comment by hexagons** [comment]
Hi, the Pod can be found here:
https://cocoapods.org/pods/PixelKit

**Comment by quinn0809** [comment]
<img width="1332" alt="WX20190612-170328@2x" src="https://user-images.githubusercontent.com/31976044/59337952-13b5ad00-8d34-11e9-95bf-4eabefe64396.png">
mabye some error for pods

**Comment by quinn0809** [comment]
will be success,As follows:
```
target 'Hello Pixels iOS' do
  use_frameworks!
  platform :ios, '11.0'

  pod 'PixelKit',:path =>'./PixelKit.podspec'

end

target 'Hello Pixels macOS' do
  use_frameworks!
  platform :osx, '10.13'

  pod 'PixelKit',:path =>'./PixelKit.podspec'

end
```
