### ISSUE TITLE
Screen Capture?

### ISSUE THREAD

**Issue by dimsky** [hexagons/PixelKit#5]
Where is the link?

**Comment by hexagons** [comment]
The docs (Jazzy) are built with the iOS version of the framework, where the Screen Capture is not available. I removed the broken link. Thanks.

**Comment by hexagons** [comment]
It's simple to use, just initialise it and it will start the screen capture:
`let screenCapture = ScreenCapturePIX()`

Then add it to a view:
```
let finalPix: PIX = screenCapture
finalPix.view.frame = view.bounds
view.addSubview(finalPix.view)
```

To choose a second screen, use this:
`screenCapture.screenIndex = 1`

**Comment by dimsky** [comment]
😔Not support iOS.
