### ISSUE TITLE
Text generation?

### ISSUE THREAD

**Issue by alyfreym** [hexagons/PixelKit#6]
Hi, is it planned to add the function of generating text in the form of a texture using  Metal API?. What methods do you know for generating text using metal? I would be very happy if you gave an example. My goal is to overlay the effect of fire on the text. thanks for the answer

**Comment by hexagons** [comment]
I don't know how to render text directly in metal, tho we got the TextPIX that renders in SpriteKit!
http://pixelkit.net/docs/Classes/TextPIX.html

**Comment by hexagons** [comment]
I've fixed the TextPIX in the latest version of PixelKit 0.6.4

**Comment by hexagons** [comment]
<img width="775" alt="Skärmavbild 2019-06-26 kl  19 38 39" src="https://user-images.githubusercontent.com/7947442/60202078-22c74f80-984a-11e9-9431-263e604e756c.png">

Here's an example of text with fire:
```
let res = PIX.Res.cgSize(view.bounds.size) * PIX.Res.scale

let textPix = TextPIX(res: res)
textPix.text = "PixelKit"
textPix.font = .monospacedSystemFont(ofSize: 200, weight: .bold)

let noisePix = NoisePIX(res: res)
noisePix.colored = true
noisePix.zoom = 0.1

let feedPix = textPix._feed(0.8) { feedPix -> (PIX & PIXOut) in
    return feedPix._displace(with: noisePix, distance: 0.1)
}

let gradientPix = GradientPIX(res: res)
gradientPix.colorSteps = [
    ColorStep(0.0, .black),
    ColorStep(1 / 3, .red),
    ColorStep(2 / 3, .yellow),
    ColorStep(1.0, .white)
]

let lookup = LookupPIX()
lookup.inPixA = feedPix
lookup.inPixB = gradientPix

finalPix = lookup + textPix
finalPix.view.frame = view.bounds
view.addSubview(finalPix.view)
```

**Comment by alyfreym** [comment]
Omg, you saved me many hours, thanks!!!!
