### ISSUE TITLE
I want to save the processed photos to the album

### ISSUE THREAD

**Issue by AllLuckly** [hexagons/PixelKit#7]
This is a very good framework, I want to save the processed photos to the album, but can't find the corresponding method, I see the code is directly loaded View:
```
           let image = ImagePIX()
            image.image = self.myImage
            let edge = EdgePIX()
            edge.input = image
            edge.strength = 3
            edge.view.frame = myImageView.bounds
            self.view.addSubview(edge.view)
```

Can't get image information of edge.view

**Comment by hexagons** [comment]
Hi, thanks!

You can get a `UIImage` from the [`.renderedImage`](http://pixelkit.net/docs/Classes/PIX.html#/s:8PixelKit3PIXC13renderedImageSo7UIImageCSgvp) method of a `PIX`.

Save code:
~~~~swift
guard let image: UIImage = edge.renderedImage else {
    print("image not avalible")
    return
}
UIImageWriteToSavedPhotosAlbum(image, nil, nil, nil)
~~~~

If the image is not available, you might need to wait until the image is loaded, like this:
~~~~swift
edge.nextTextureAvalible {
    // save code here
}
~~~~

Remember to add `NSPhotoLibraryUsageDescription` to your info.plist.

**Comment by AllLuckly** [comment]
is very good!👍🏻
