### ISSUE TITLE
Unresolved identifier 'ImagePIXUI'

### ISSUE THREAD

**Issue by SirWindfield** [hexagons/PixelKit#8]
I've added PixelKit to my Podfile and installed it. Xcode does pick it up and I can import it and use the UIKit related part without problems. However, I can't use SwiftUI related types as those don't get resolved by Xcode.

**Comment by hexagons** [comment]
Just tested and it works on my end. Could you post some example code?
Also make sure to run `pod update` to get the latest version of the pod.

**Comment by hexagons** [comment]
@SirWindfield Did you ever get it to build?
Let me know if it still dose not work, I can help you get it going!

**Comment by SirWindfield** [comment]
Sadly not, no. Running `pod update` did nothing, which I would guess means that I have the latest version already attached to the project. For some odd reasons it just doesn't compile properly. I went into the folder of the PixelKit dependency and none of the swift related UI component files are present. Which is just weird to me :(

**Comment by hexagons** [comment]
Hm, ok, if you check your Podfile.lock file, what version of PixelKit are you using?
