### ISSUE TITLE
Pixelkit not conforming to latest RenderKit changes

### ISSUE THREAD

**Issue by intonarumori** [hexagons/PixelKit#9]
Couple of files in this project do not conform to `NodeMetal` protocol.
Specifically `metalFileName` property introduced [here](https://github.com/hexagons/RenderKit/commit/4e147502c01a9488145c2f04351683354a2cea24) is missing for multiple files ex. `MetalMergerEffectPIX`.

**Comment by hexagons** [comment]
So `metalFileName` is not used anymore,
`metalBaseCode` replaces this property.

Sorry this change was made in a patch update.

The update "hardcodes metal" (PixelKit 1.0.2 & RenderKit 0.4.0) is an update to eliminate bundle resources, as SwiftPM dose not support this yet. The MetalPIXs should conform to the updated NodeMetal protocol.

What versions of PixelKit and RenderKit are you using?
Are you using Pods or SwiftPM?

**Comment by intonarumori** [comment]
I was just trying the iOS example in the project.
Here are the steps:
- Downloaded the zip from Github
- Ran `git submodule init` to get the shaders
- Ran `pod install` to get the dependencies
- Build failed with errors

To fix the errors I made `MetalPix`, `MetalEffectPix`, `MetalMergerEffectPIX`, `MetalMultiEffectPIX` conform to `NODEMetal` by adding the following:  
`public var metalFileName: String = ""`

I also added a convenience method to `Render` to be able to either load Metal code as string or from a file:
```

    public func embedMetalCode(uniforms: [MetalUniform], code: String, fileName: String) throws -> String {
        guard let bundle: Bundle = bundle else {
            throw MetalError.fileNotFound("No bundle provided. Can't look for file \"\(fileName).txt\"")
        }
        guard let metalFile = bundle.url(forResource: fileName, withExtension: "txt") else {
            throw MetalError.fileNotFound(fileName + ".txt")
        }
        do {
            let metalCode = try String(contentsOf: metalFile)
            return try embedMetalCode(uniforms: uniforms, code: code, metalBaseCode: metalCode)
        } catch {
            throw error
        }
    }

public func embedMetalCode(uniforms: [MetalUniform], code: String, metalBaseCode: String) throws -> String {
        do {
            var metalCode = metalBaseCode
            let uniformsCode = try dynamicUniforms(uniforms: uniforms)
            metalCode = try insert(uniformsCode, in: metalCode, at: "uniforms")
            let comment = "/// PixelKit Dynamic Shader Code"
            metalCode = try insert("\(comment)\n\n\n\(code)\n", in: metalCode, at: "code")
            #if DEBUG
            if logger.dynamicShaderCode {
                print("\nDYNAMIC SHADER CODE\n\n>>>>>>>>>>>>>>>>>\n\n\(metalCode)\n<<<<<<<<<<<<<<<<<\n")
            }
            #endif
            return metalCode
        } catch {
            throw error
        }
    }
```

With all of these the example did compile and I was able to test the different nodes, great project. If you experience the same with the example please consider fixing it, many thanks.

**Comment by hexagons** [comment]
Nice fix,
I'm glad you got it working.

So I was able to reproduce the issue. It was caused by a missmatch of RenderKit and PixelKit versions.
I've switched over to swiftpm from pods for development and forgot to push the RenderKit pod.
New versions of RenderKit 0.4.2 and PixelKit 1.0.4 contains the fix.

Thanks,
/Anton
